package se.statenspersonadressregister.referensimplementation;

public class PersonSokExempelLogTexter {
    public static final char RADBRYT = '\n';
    public static final String PERSON_ID = "  PersonId = ";
    public static final String DATUM_FROM = "    Datum from = ";
    public static final String DATUM_TILL = "    Datum till = ";
    public static final String AVREGISTRERINGSDATUM = "    Avregistreringsdatum = ";
    public static final String AVREGISTRERINGSORSAK_KOD = "    AvregistreringsorsakKod = ";
    public static final String FÖRNAMN = "    Förnamn = ";
    public static final String MELLANNAMN = "    Mellannamn = ";
    public static final String EFTERNAMN = "    Efternamn = ";
    public static final String AVISERINGSNAMN = "    Aviseringsnamn = ";
    public static final String TILLTALSNAMN = "    Tilltalsnamn = ";
    public static final String FÖDELSELAN_KOD = "    FödelselanKod = ";
    public static final String FÖDELSEFORSAMLING = "    Födelseforsamling = ";
    public static final String FÖDELSETID = "    Födelsetid = ";
    public static final String HÄNVISNINGS_PERSON_NR_BYTT_FRÅN = "    HänvisningsPersonNrByttFrån = ";
    public static final String HÄNVISNINGS_PERSON_NR_BYTT_TILL = "    HänvisningsPersonNrByttTill = ";
    public static final String SEKRETESSMARKERING1 = "  Sekretessmarkering = ";
    public static final String SEKRETESSMARKERING2 = "    Sekretessmarkering = ";
    public static final String KÖN = "    Kön = ";
    public static final String KOD = "  Kod = ";
    public static final String BESKRIVNING = "  Beskrivning = ";
    public static final String AVISERINGSPOST = "Aviseringspost";
    public static final String PERSONDETALJ = "  Persondetalj";
    public static final String MELLANSLAG = " ";
    public static final String SOKTRAFFAR = " sökträffar, ";
    public static final String ANTALUNDANTAG = " undantag";
    public static final String OVERSTIGER_MAX_ANTAL_TRAFFAR = "  Överstiger maximalt antal träffar, ";
    public static final String TRAFFAR_AV_MAX = " träffar av maximalt ";
    public static final String SPARPERSONSOKNING_SVAR = "SPARPersonsokningSvar:";
    public static final String UNDANTAG = "Undantag";
    public static final String BESKATTNINGSAR = "  Beskattningsår = ";
    public static final String SUMMERAD_INKOMST = "  SummeradInkomst = ";
    public static final String SEKRETESS_ANDRINGSDATUM = "  SekretessÄndringsdatum = ";
    public static final String SENASTE_ANDRING_SPAR = "  SenasteAndringSPAR = ";
    public static final String RELATIONSTYP = "  Relationstyp = ";
    public static final String RELATION = "Relation";
    public static final String CARE_OF = "    Care of = ";
    public static final String UTDELNINGSADRESS_1 = "    Utdelningsadress 1 = ";
    public static final String UTDELNINGSADRESS_2 = "    Utdelningsadress 2 = ";
    public static final String UTDELNINGSADRESS_3 = "    Utdelningsadress 3 = ";
    public static final String POSTORT = "    Postort = ";
    public static final String POSTNUMMER = "    Postnummer = ";
    public static final String FOLKBOKFÖRINGSADRESS = "  Folkbokföringsadress";
    public static final String FOLKBOKFORDSFÖRSAMLINGKOD = "    Folkbokfordsförsamlingkod = ";
    public static final String DISTRIKTKOD = "    Distriktkod = ";
    public static final String KOMMUNKOD = "    Kommunkod = ";
    public static final String LANKOD = "    Länkod = ";
    public static final String UTLANDSADRESS = "  Utlandsadress";
    public static final String SARSKILD_POSTADRESS = "  Särskild postadress";
    public static final String LAND = "    Land = ";
    public static final String FASTIGHET = "  Fastighet";
    public static final String FASTIGHETSKOD = "    Fastighetskod = ";
    public static final String KOMMUN = "    Kommun = ";
    public static final String LAN = "    Län = ";
    public static final String TAXERINGSAR = "    Taxeringsår = ";
    public static final String TAXERINGSVARDE = "    Taxeringsvärde = ";
    public static final String ANDELSTAL_TALJARE = "    Andelstal täljare = ";
    public static final String ANDELSTAL_NAMNARE = "    Andelstal nämnare = ";
}
